server:
  port: 8771
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: null
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      namingStrategie: org.hibernate.cfg.DefaultNamingStrategy
      ddlAuto: create-drop
    show-sql: true

