server:
  port: 8771
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: null
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      namingStrategie: org.hibernate.cfg.DefaultNamingStrategy
      ddlAuto: create-drop
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.ws: DEBUG
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/